version: '3.7'

services:
    php-httpd:
        image: php:7.4-apache
        ports:
            - "80:80"
        volumes:
            - "$PWD/website:/var/www/html"

    mariadb:
        image: mariadb:10.5.2
        volumes:
            - "mariadb-volume:/var/lib/mysql"
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'douglas'
            MYSQL_PASSWORD: 'douglas'
            MYSQL_DATABASE: 'teste'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - "8081:80"
    
    javascript:
        image: javascriphpt/web:latest
        volumes:
            - "$PWD/website:/var/www/html"


volumes:
    mariadb-volume: