version: '2.0'
services:
  omv:
     container_name: omv
     build: ./build
     volumes:
      - "./var/www/openmediavault/js/omv/module/admin/service/webdesk:/var/www/openmediavault/js/omv/module/admin/service/webdesk"
      - "./var/www/openmediavault/js/omv/module/admin/diagnostic/log/plugin/WebDesk.js:/var/www/openmediavault/js/omv/module/admin/diagnostic/log/plugin/WebDesk.js"
      - "./var/www/openmediavault/images/webdesk:/var/www/openmediavault/images/webdesk"
      - "./usr/share/openmediavault/engined/inc/90webdesk.inc:/usr/share/openmediavault/engined/inc/90webdesk.inc"
      - "./usr/share/openmediavault/engined/rpc/webdesk.inc:/usr/share/openmediavault/engined/rpc/webdesk.inc"
      - "./usr/share/openmediavault/engined/module/webdesk.inc:/usr/share/openmediavault/engined/module/webdesk.inc"
      - "./usr/share/openmediavault/locale/en_US/openmediavault-webdesk.po:/usr/share/openmediavault/locale/en_US/openmediavault-webdesk.po"
      - "./usr/share/openmediavault/locale/fr/openmediavault-webdesk.po:/usr/share/openmediavault/locale/fr/openmediavault-webdesk.po"
      - "./usr/share/openmediavault/locale/fr_FR/openmediavault-webdesk.po:/usr/share/openmediavault/locale/fr_FR/openmediavault-webdesk.po"
      - "./usr/share/openmediavault/locale/openmediavault-webdesk.po:/usr/share/openmediavault/locale/openmediavault-webdesk.po"
      - "./usr/share/openmediavault/datamodels/conf.service.webdesk.json:/usr/share/openmediavault/datamodels/conf.service.webdesk.json"
      - "./usr/share/openmediavault/datamodels/conf.service.webdesk.link.json:/usr/share/openmediavault/datamodels/conf.service.webdesk.link.json"
      - "./usr/share/openmediavault/datamodels/rpc.webdesk.json:/usr/share/openmediavault/datamodels/rpc.webdesk.json"
      - "./usr/share/openmediavault/mkconf/nginx.d/90-webdesk:/usr/share/openmediavault/mkconf/nginx.d/90-webdesk"
      - "./usr/share/openmediavault/mkconf/phpfpm.d/90-webdesk:/usr/share/openmediavault/mkconf/phpfpm.d/90-webdesk"
      - "./etc/webdesk:/etc/webdesk"
      - "./debian:/var/www/debian"
      - "./bin:/var/www/bin"
     restart: always
     working_dir: /var/www/debian
     ports:
     - "0:80"
     - "0:22"
     - "0:90"
     - "0:3000"
     networks:
      default:
       aliases:
        - "openmediavault.plugin.test"
