version: "3.3"

services:

  cloud9:
    image: lscr.io/linuxserver/cloud9:latest
    container_name: cloud9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - GITURL=https://github.com/linuxserver/docker-cloud9.git #optional
      - USERNAME=user #optional
      - PASSWORD=p4ssw0rd #optional
    volumes:
      - /cloud9:/code #optional
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - "8200:8000"
    restart: unless-stopped
